import { describe, expect, it } from 'vitest';
import { FREQUENCY } from '@/constant.ts';
import type { DBExpense } from '@/database/expenses.ts';
import { occurrencesInMonth } from '@/lib/recurrence.ts';
import { createDutiesForSelectedDateRange } from '../duties.service.ts';

/**
 * That the two screens are talking about the same money.
 *
 * The duties table shows occurrences, generated by walking the days of a range. The expenses
 * table shows what those occurrences cost, arrived at by counting them with a formula. Two
 * independent implementations of one rule, on two screens, under two totals — and when they
 * disagree there is nothing on either screen to say which is wrong.
 *
 * So the property is pinned here rather than trusted: for any month, as many duties are
 * generated as `occurrencesInMonth` says there are.
 */

const AUGUST_2026 = { start: new Date(2026, 7, 1), end: new Date(2026, 7, 31, 23, 59, 59) };
const FEBRUARY_2027 = { start: new Date(2027, 1, 1), end: new Date(2027, 1, 28, 23, 59, 59) };

const expense = (frequency: FREQUENCY, execution: Date): DBExpense =>
  ({
    id: `${frequency}-${execution.toISOString()}`,
    description: frequency,
    expense: 100,
    currency: 'PLN',
    severity: null,
    frequency,
    execution,
  }) as DBExpense;

const generatedCount = async (item: DBExpense, range: { start: Date; end: Date }) => {
  const duties = await createDutiesForSelectedDateRange({
    expenses: [item],
    startDate: range.start,
    endDate: range.end,
  });

  return duties.length;
};

const counted = (item: DBExpense, month: { year: number; monthIndex: number }) =>
  occurrencesInMonth(item, month);

describe('the duty generator and the occurrence count agree', () => {
  const august = { year: 2026, monthIndex: 7 };

  // A Wednesday in July. August 2026 holds four of them.
  const WEDNESDAY = new Date(2026, 6, 15);

  it.each([
    ['daily', FREQUENCY.DAILY],
    ['weekly', FREQUENCY.WEEKLY],
    ['monthly', FREQUENCY.MONTHLY],
  ])('for a %s cost', async (_name, frequency) => {
    const item = expense(frequency, WEDNESDAY);

    expect(await generatedCount(item, AUGUST_2026)).toBe(counted(item, august));
  });

  it('for a yearly cost, in the month it falls in', async () => {
    const item = expense(FREQUENCY.YEARLY, new Date(2026, 7, 15));

    expect(await generatedCount(item, AUGUST_2026)).toBe(1);
    expect(counted(item, august)).toBe(1);
  });

  it('for a yearly cost, in a month it does not fall in', async () => {
    const item = expense(FREQUENCY.YEARLY, new Date(2026, 6, 15));

    expect(await generatedCount(item, AUGUST_2026)).toBe(0);
    expect(counted(item, august)).toBe(0);
  });

  /**
   * The 31st in a month that has no 31st.
   *
   * Kept as its own case because it is where two implementations of "once a month" are most
   * likely to part company: one asks how many months are in the range, the other builds a date
   * and lets the calendar answer.
   */
  it('for a monthly cost due on a day the month does not have', async () => {
    const item = expense(FREQUENCY.MONTHLY, new Date(2026, 0, 31));

    expect(await generatedCount(item, FEBRUARY_2027)).toBe(
      counted(item, { year: 2027, monthIndex: 1 })
    );
  });

  it('and puts that occurrence on the last day the month does have', async () => {
    const item = expense(FREQUENCY.MONTHLY, new Date(2026, 0, 31));

    const [duty] = await createDutiesForSelectedDateRange({
      expenses: [item],
      startDate: FEBRUARY_2027.start,
      endDate: FEBRUARY_2027.end,
    });

    expect(duty.executionDate.getDate()).toBe(28);
  });

  it('for a monthly cost due on the 31st of a thirty-day month', async () => {
    // April, June, September and November are the other four this used to fall out of.
    const april = { start: new Date(2027, 3, 1), end: new Date(2027, 3, 30, 23, 59, 59) };
    const item = expense(FREQUENCY.MONTHLY, new Date(2026, 0, 31));

    expect(await generatedCount(item, april)).toBe(counted(item, { year: 2027, monthIndex: 3 }));
  });
});
